### ISSUE TITLE
Expected WebSocket Upgrade request

### ISSUE THREAD

**Issue by luliu** [ruippeixotog/scalafbp#3]
Hello, after running the docker run command on OS X and trying to hit http://localhost:3569   I get a "Expected WebSocket Upgrade request" message.  Any idea why?

**Comment by ruippeixotog** [comment]
Hi @luliu, thanks for reporting this! It seems that it was a bug introduced in ea2a07c1470e6fd04b3e893d4a32e9b590f1a0c8 in which the server doesn't distinguish between WebSocket and normal HTTP requests in the same endpoint. I reverted the Docker image temporarily to the previous commit and it now works as expected, you can try it now! I'll fix this soon.

**Comment by luliu** [comment]
Sweet.  Thank you!

**Comment by ruippeixotog** [comment]
Fixed by 04e663e8204e027f074ce8486bd333f8052053a0.
